markdown: rdiscount
pygments: true
permalink: /posts/:title
auto: true
rdiscount:
  extensions: [smart]
title : Get EU!
production_url : http://get-eu.org/
description: "Debate about the European Union"
disqus_shortname: caarlos0blog
#analytics: UA-32899481-1
#gauges: 50f2b533613f5d7c8000000c
author :
  name : Martin Keegan
  github : mk270
  twitter : mk270
  email: martin@no.ucant.org
